version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
      - run: 
          name: build dependencies
          command: bundle install
          
      - run: 
          name: build the jekyll site
          command: bundle exec jekyll build
          
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
      - run:
          name: print date
          command: date

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
